### ISSUE TITLE
Golua, released by Microsoft.  Anything interesting to learn from? 

### ISSUE THREAD

**Issue by naturallymitchell** [amethyst/rlua#100]
~~What do you guys think of this new Lua runtime and its prospects for use in Rust?~~  [Azure/golua](https://github.com/Azure/golua)

**Comment by mitchtbaum** [comment]
It's an interesting project, but not relevant to Rust (afaict: https://news.ycombinator.com/item?id=18470201).  I'll change the question above in case any rlua users have anything interesting reactions to Golua.

**Comment by jugglerchris** [comment]
Closing, as this is not an issue for rlua.
