### ISSUE TITLE
`load` / `loadfile` lua functions can load arbitrary bytecode

### ISSUE THREAD

**Issue by kyren** [amethyst/rlua#116]
AIUI this can be used to cause the interpreter to exhibit UB.

`load` and `loadfile` need to be wrapped so that the `mode` flag does not do anything, but unlike pcall / xpcall wrapping, this really seems to break the API of those functions.

There has to be the ability to turn these wrappers off, just like there is the ability to force load the `debug` library, and similarly it will have to be behind an unsafe flag.

The `load `and `loadfile` wrappers shouldn't be too bad, and configuring them could be as simple as adding a flag to `StdLib` that disables wrapping `load` / `loadfile`, though that breaks the `StdLib` <=> 'library' equivalence.

Probably this has to be a new 0.x version bump as well 😞

**Comment by kyren** [comment]
Also `package.loadlib` allows a script to load a C library, which is also really unsafe.

Am I missing any more?

**Comment by kyren** [comment]
Okay, here is a list of everything that I think is potentially unsafe, some of it may simply have to be not loaded *at all*.  Currently only `debug` is guarded against:

- [ ] dofile
- [ ] load
- [ ] loadfile
- [ ] os.setlocale
- [ ] package.loadlib
- [ ] os.date (maybe, might be fixed in 5.2, might be considered a bug)
- [x] debug (okay, technically *some* of debug might be safe, but is of questionable use by itself)

**Comment by kyren** [comment]
It might be simpler to set package.path to "" disallow package.* entirely, as package.path should not be allowed to be set at all.  Without setting package.path to empty string, `require` becomes unsafe.

**Comment by jugglerchris** [comment]
I have spun out #237 (`os.date`) and #238 (`os.setlocale`) as I think they're less serious.
The others are now wrapped or removed by default, with `InitFlags` which can be disabled to allow the originals.
