### ISSUE TITLE
Best way to store a value of dynamic type in rust from lua

### ISSUE THREAD

**Issue by surajprak** [amethyst/rlua#126]
My lua code calculates result which, it can save to a table in lua. I also want to save these values in rust which lua can pass
It can be of following type
HashMap<T, HashMap<X,Y>> 
where T can in int, float, long, String etc. X can be same as T or can be HashMap
HashMap<T, Vec<X1>>
Vec<T>
Vec<Vec<T>>

What is the best way of doing it?

**Comment by surajpayu** [comment]
For e.g.
I have a lua table whose pretty print is below
{ 
  category = {},
  ibibo_code = { 
    ["'netbanking'"] = { { 
        amount_lower_limit = '0',
        cardtype = 'default',
        category = "'netbanking'",
        flat_fee = '0',
        ibibo_code = {},
        on_us = false,
        percent_fee = '2',
        pg = {},
        value = 
        [['{\"default\":{\"0\":{\"flatFee\":\"0\",\"percentFee\":\"2\"},\"10000\":{\"fla
        tFee\":\"0\",\"percentFee\":\"1.60\"}}}']] 
      }, { 
        amount_lower_limit = '10000',
        cardtype = 'default',
        category = "'netbanking'",
        flat_fee = '0',
        ibibo_code = {},
        on_us = false,
        percent_fee = '1.60',
        pg = {},
        value = 
        [['{\"default\":{\"0\":{\"flatFee\":\"0\",\"percentFee\":\"2\"},\"10000\":{\"fla
        tFee\":\"0\",\"percentFee\":\"1.60\"}}}']] 
      } } 
  },
  pg = { 
    ['8'] = { { 
        cardtype = 'default',
        category = "'creditcard'",
        flat_fee = '0',
        ibibo_code = {},
        on_us = false,
        percent_fee = '1.58',
        pg = '8',
        value = 
        [['{\"default\":[{\"flatFee\":\"0\",\"percentFee\":\"1.58\"}],\"on_us\":[{\"flat
        Fee\":\"0\",\"percentFee\":\"1.45\"}]}']] 
      }, { 
        category = "'creditcard'",
        flat_fee = '0',
        ibibo_code = {},
        on_us = true,
        percent_fee = '1.45',
        pg = '8',
        value = 
        [['{\"default\":[{\"flatFee\":\"0\",\"percentFee\":\"1.58\"}],\"on_us\":[{\"flat
        Fee\":\"0\",\"percentFee\":\"1.45\"}]}']] 
      } } 
  } 
}

I want to pass this table from lua to rust and store it inside rust as a hashmap.

**Comment by jugglerchris** [comment]
This is more of a Rust design question - you would need to come up with a suitable Rust type to represent your values.  This could be something quite general similar to a [JsonValue](https://docs.rs/json/0.12.4/json/enum.JsonValue.html) from the Json crate, or something more specific to your application.  You would then implement `FromLua` to convert into your type.

I am closing as this issue is now quite old and I don't think there's anything still to do on the rlua side.

**Comment by singalen** [comment]
I think the question describes a pretty basic need: store a `rlua::Value` outside of `lua.context()`, when the value might be as complex as a Table.

It's not a problem for primitive types, they already have or can have a trivial `FromLua`/`ToLua` implementations.

In my case, I need to save a `Table`, of course, without `LightUserData`, `UserData`, `Function`, `Thread` and `Error`, but including Tables of arbitrary depth with any other Values in them. Implementing my own structure just to repeat `rlua::Value` feels too boilerplate.

I guess that such a function would be useful to more than one user.

I'll take a stab at using `JsonValue` as a such storage and will share the results if it works well.

**Comment by jugglerchris** [comment]
Sounds good - let us know how it goes!

**Comment by singalen** [comment]
There's a first version: https://github.com/singalen/rlua_json
I'm yet to test it in the field.
