### ISSUE TITLE
how do i do static initialization of functions exposed to lua

### ISSUE THREAD

**Issue by surajprak** [amethyst/rlua#128]
I am doing following task when i interact with lua from rust.
I have a lua helper function in rust(let's name it call_lua), which does following tasl
call_lua(input)
1) load lua script which i need to call
2) create some rust functions, methods using lua_ctx 
3) create a lua thread
4) use this thread inside a mpsc receiver(rx_inner) and resuming it for each message on receiver rx_inner.

I do not want to redo step 1 and step 2 for each call to call_lua would like to initialize them once only. i would like to convert it into a event loop using another mpsc receiver after point 2
So call_lua can be replaced by lua_eventloop() which does following - 
lua_eventloop(){
1) load lua script which i need to call
2) create some rust functions, methods using lua_ctx 
rx.for_each(|input|{
   3) create a lua thread
   4) use this thread inside a mpsc receiver(rx_inner) and resuming it for each message on receiver rx_inner.
}
);

Its not possible to do it as lua_state which is part of lua_ctx is not static and since lua state  can not be shared across different thread(https://github.com/kyren/rlua/issues/119#issuecomment-464747923)
Is their some way, i can achieve my desired goal of not re-doing point 1 and 2 again and again?

**Comment by jugglerchris** [comment]
Hi,
I'm not sure I understand the question.  If you want to access the Lua state from multiple threads then you can't directly - you would have to create multiple instances of Lua states or go via a `Mutex`.
Closing as this ticket is now quite old and I don't believe there's anything currently to do in rlua.
