### ISSUE TITLE
Any way to preload a library written in Rust?

### ISSUE THREAD

**Issue by lbrowne** [amethyst/rlua#131]
I'm looking for a way to preload libraries so they can be included in a script via `require`. This comment in `linit.c` describes what I'm trying to do:
```
** You can also *preload* libraries, so that a later 'require' can
** open the library, which is already linked to the application.
** For that, do the following code:
**
**  luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_PRELOAD_TABLE);
**  lua_pushcfunction(L, luaopen_modname);
**  lua_setfield(L, -2, modname);
**  lua_pop(L, 1);  // remove PRELOAD table
```

I thought about writing in the functionality myself but after reading this issue (https://github.com/kyren/rlua/issues/105), it looks like it might be a little trickier than I thought. I'm not well-versed in the internals of Lua, I'm hoping someone might have some insight on how to go about this.

**Comment by jugglerchris** [comment]
What kind of libraries do you want to preload?
If you're adding functions implemented in Rust (or Lua) from an application using rlua, then I would do one of:
* Create your module as a table and assign it to `package.loaded["module_name"]`
* If the setup is more extensive, put a function to load/create the module into `package.preload["module_name"]`.  It will be called on the first `require("module_name")`.

Both `package.loaded` and `package.preload` can be accessed directly in Lua code or via [LuaContext::globals()](https://docs.rs/rlua/0.17.0/rlua/struct.Context.html#method.globals).

I'm closing this issue as it's now quite old and I hope it has been answered.  Please re-open if more is needed.
