### ISSUE TITLE
get_user_value works differently than AnyUserData::is?

### ISSUE THREAD

**Issue by TheDan64** [amethyst/rlua#134]
Thanks for working on this great library!

I've got a question that has me a bit stumped. I've got some code that looks like:

```rust
#[derive(Clone, Debug)]
pub struct Wrapper(T); // Where T is some external, concrete type that impls Clone, Debug

impl UserData for Wrapper {}
```

```rust
table.set("wrapper", Wrapper(t))?;
```

and elsewhere:

```rust
let data: AnyUserData = table.get("wrapper")?;

assert!(data.is::<Wrapper>()); // Ok

let _ = data.get_user_value::<Wrapper>()?; // FromLuaConversionError { from: "nil", to: "userdata", message: None}
```

Maybe I'm misunderstanding the API here, but shouldn't `get_user_value` get you an owned `Wrapper`? The `is` method suggests that it was actually found and not nil. And `FromLua` is impl'd for `'static + UserData + Clone` so I would expect it to be able to pull up my `Wrapper` type

**Comment by TheDan64** [comment]
Silly me just realized that I really should just be doing
```rust
let data: Wrapper = table.get("wrapper")?
```

**Comment by kyren** [comment]
Glad you figured it out!  Some background info for context:

`AnyUserData::get_user_value` / `AnyUserData::set_user_value` are *terribly* named, but the name comes from PUC-Lua so I'm not sure what to do about it.

Lua has a concept of "user values" that are associated with a "userdata", where "userdata" is a block of memory that Lua provides that allows the user to place anything they want in it, and can have its own metatable.

I really really wish they called it something other than "user value", but it is a value *associated* with a "userdata" that Lua understands and can be garbage collected.  You can't store garbage collected references inside userdata sensibly at all in Lua, and the creators of Lua realized this, so the associated "user value" values are a way to solve this and tie Lua values with userdata in a way that the Lua garbage collector understands.

These rlua methods correspond to `lua_getuservalue` and `lua_setuservalue` which are described in [the manual](https://www.lua.org/manual/5.3/manual.html#lua_setuservalue).

I should probably just pick better names, like maybe `get_associated_value` and `set_associated_value`, as `get_user_value` and `set_user_value` are *very* generic and confusing.

**Comment by TheDan64** [comment]
Ahhh thanks for clarifying! +1 for `associated` as it helps convey that it's a related, but separate value.
