### ISSUE TITLE
Does doing a Lua::new() create a new OS thread?

### ISSUE THREAD

**Issue by surajprak** [amethyst/rlua#135]
``` 
fn test(){
    let lua = Lua::new();
    lua::lua.context(|lua_ctx| {
    ....
   });
   let s = "suraj".to_string();
}
```
I am bit curious to know that when I run above code does it create a new OS thread for executing lua part or does it use the same OS thread in which my rust code is running and calling Lua::new() from.

**Comment by bluss** [comment]
It does not create a new thread
