### ISSUE TITLE
Setting nil on a table does not work on arrays

### ISSUE THREAD

**Issue by althonos** [amethyst/rlua#138]
Hi !

The only way in `rlua` to remove a value from a table is to set it to `nil`: however, on arrays, this has not the expected behaviour, simply setting that index to `nil` instead of removing that value and shifting the other values from the array to the left. That means there is not way to remove a value by position (like `table.remove` does) from Rust code (or I am mistaken ?).

**Comment by kyren** [comment]
The `Table` type is missing APIs for things like `table.remove`, but I don't think that functionality exists directly in the Lua C API in the first place?

If it's just a one off thing, you can always go through lua to call a lua stdlib function from rust to do what you want, or even get a handle to the `table.remove` function.

If there's something in the Lua C API that does that though I can expose it.  Even if it's not available directly like that I wouldn't say that I *definitely* wouldn't want to add it, I'd have to think about it some more.

**Comment by jugglerchris** [comment]
Closing as I think this has been answered.
