### ISSUE TITLE
Loading and running bytecode

### ISSUE THREAD

**Issue by elice02** [amethyst/rlua#145]
Hi,

I have been trying to run some bytecode using this:

let mut f = File::open("C:\\Users\\kkp\\Documents\\Rust\\server_host\\src\\out.luac").unwrap();
let mut buffer = Vec::new();
f.read_to_end(&mut buffer);
lua_ctx.load(&*buffer).exec().is_err();

but I can't get it to work. Do you have any idea how to execute pre-compiled bytecode from a file?

**Comment by kyren** [comment]
The reason for that is that it's potential UB and needs a separate unsafe interface, which I've yet to add.

**Comment by elice02** [comment]
I'm not sure why executing bytecode is considered so insecure? It's part of Lua and is no more or less secure than running arbitrary Lua scripts. Running scripts or bytecode from any insecure resource is a security risk, whether compiled or not. Obviously, scripts allow you to read the content, but that's not really relevant for me. Having precompiled content significantly speeds up what I'm trying to do.

**Comment by kyren** [comment]
It's not that it's insecure, it's that it's actually UB if the bytecode is malformed.  As I understand it, there's no bounds checking on the indexes in the bytecode, so if the bytecode is corrupted or something it will just exhibit UB.

I'm not saying you shouldn't have the ability to do this, I'm just saying it needs a separate unsafe function to do it.

If you really need to do this right now you can do it by going through lua's `loadfile` function instead, which I realize is not super ergonomic.

This is sort of related to #116, I just haven't had time lately to actually sit down and solve all of this.

**Comment by elice02** [comment]
ah ok, I get it. Thanks for the response. I think I will load the file from the file system for now using loadfile. :-)

Many thanks.
