### ISSUE TITLE
Get bytecode of the chunk

### ISSUE THREAD

**Issue by calebwin** [amethyst/rlua#153]
Is there a way to get the `source: &[u8]` from a `Chunk`? As long as it's read-only, there shouldn't be any UB. Right?

**Comment by calebwin** [comment]
Here's [a PR](https://github.com/kyren/rlua/pull/154). Just needs a `cargo fmt` I think.

**Comment by jugglerchris** [comment]
Closing; as discussed in #154 getting the source to a `Chunk` isn't what's actually wanted.
