### ISSUE TITLE
ios wont compile

### ISSUE THREAD

**Issue by aentity** [amethyst/rlua#168]
Attempting compile for `--target=aarch64-apple-ios` has:
```
Detecting iOS SDK path for iphoneos
running: "cc" "-O0" "-fPIC" "-g" "-fno-omit-frame-pointer" "-arch" "arm64" "-miphoneos-version-min=7.0" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk" "-fembed-bitcode" "-I" "lua" "-Wall" "-Wextra" "-DLUA_USE_POSIX" "-DLUA_USE_APICHECK" "-o" "/Users/aentity/test/target/aarch64-apple-ios/debug/build/rlua-e345682ccd9c93a6/out/lua/loslib.o" "-c" "lua/loslib.c"
cargo:warning=lua/loslib.c:143:14: error: 'system' is unavailable: not available on iOS
cargo:warning=  int stat = system(cmd);
cargo:warning=             ^
cargo:warning=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/usr/include/stdlib.h:190:6: note: 'system' has been explicitly marked unavailable here
cargo:warning=int      system(const char *) __DARWIN_ALIAS_C(system);
cargo:warning=         ^
cargo:warning=1 error generated.
exit code: 1
 error: 'system' is unavailable: not available on iOS
```

Is possible to somehow provide solutions here? http://lua-users.org/lists/lua-l/2017-09/msg00242.html

**Comment by kyren** [comment]
You should be able to compile lua yourself and link it in yourself, rather than try to compile the version that is shipped with rlua.

You can turn off the `builtin-lua` feature and either turn on the `system-lua` feature which will try to find lua5.3 from pkg-config, or just leave both features off and link Lua yourself, that way you can patch Lua however you need to.

**Comment by aentity** [comment]
Hi sorry for delay, yes thank you! Turning off default features, i can resolve lua symbols by making own static library.
I used https://github.com/chublix/lua-ios and changed build a little to make static library. I can then use rlua on ios, thank you so much for suggestion and library!

We can close if you want, hopefully others can read your comment and try same if needed, and use link lua-ios to make selves.
