### ISSUE TITLE
rlua is now part of the Amethyst organisation

### ISSUE THREAD

**Issue by erlend-sh** [amethyst/rlua#174]
`rlua` is now part of the [Amethyst organisation](https://github.com/amethyst)! 🎉 We will be co-maintaining this project together with @kyren and [whoever else](https://github.com/search?q=rlua+filename%3ACargo.toml&type=Code) wants to become involved. 🤝 

### How did this happen?

I've been chatting asynchronously with @kyren for the past two weeks regarding https://github.com/amethyst/rlua/issues/172.

Her *ask* boils down to what is also a very generous offer:

> I'll happily be around to help with the hard parts. What it needs though is better leadership and organization skills than I have or at least have to spare currently.

This is exactly the sort of overhead the Amethyst org can cheaply absorb into our existing processes and structures. In the less abstract: For now we'll just take care of granting the necessary GitHub privileges to any willing contributors. There are a handful of active `rlua` users with a real stake in its continued maintenance and even betterment. Amethyst org will help facilitate the onboarding of the people who raise their hand up to help.

### Handing out access

All repeat-contributors have been granted Triage access: @lemarcuspoilus, @Timidger, @jonas-schievink, @Shiroy. @azdle already has Write access.

@rustysec, @jugglerchris and @Grokmoo have all expressed an interest in *co*-maintaining, so you've all been set up with Maintain access. You aren't committed to anything, but it should be easy for you to take action if you find an opportunity to do so. 🦸 

@khvzak also has Maintain access. Whether or not we are able to find a way to directly collaborate, `rlua` and `mlua` have way more in common than not; cross-pollination is encouraged. 🐝 

---

Feel free to ask org-related questions here, or join the Amethyst #scripting channel on Discord: https://discord.gg/KqkvQsC

**Comment by Timidger** [comment]
I'm not really involved with or use this project any more, there's no need for me to have triage access.

**Comment by jugglerchris** [comment]
Thanks!  I need to enable two-factor authentication before joining - any recommendations for Android apps?

**Comment by erlend-sh** [comment]
I just use the Google Authenticator app, but GitHub makes some other recommendations here:
https://help.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication#configuring-two-factor-authentication-using-a-totp-mobile-app

**Comment by lemarcuspoilus** [comment]
I'm happy to know rlua is potentially going to have more attention!

I appreciate previous constributors have been given some access to assist the repository, including me with my single pull request. This is surprising to not say the least!

Currently, I'm not doing much contributions to open source projects. However, I'm considering the use of rlua for a project, where `no-std` and embedded support is a requirement. If that's the case, then I'll be doing the changes needed for the support to occur, and likely submit a pull request if it doesn't involve too many changes (or if you are interested in it).

Hope to see support for the upcoming Lua 5.4 runtime!

**Comment by steelx** [comment]
That's great news. Seeing such good updates will help keep Rust gaming community pumping :)

**Comment by jugglerchris** [comment]
This has been fairly quiet, and there are some new (and a few old) PRs with not much response.

So, @rustysec @Grokmoo @khvzak (or anyone else) - do you still want to be involved?  If so I think we should agree on how decisions are made.

If not (or if I don't get any reply in the next week or two) then I'll start accepting and/or making changes as I see fit, taking into account how I think @kyren might like things to go.  I still don't have the time to do this full time, but I'm happy to do light maintenance - approving/merging PRs which look good to me and occasionally looking into things myself as I need to/find time for - but with no guarantee I'd get around to much!

**Comment by rustysec** [comment]
I was actually looking at some PRs last week but just didn't have time to give them any kind of thorough review. I'd like to help the project any way I can, but I'm in a similar situation (not having as much time as I'd like).

**Comment by jugglerchris** [comment]
In that case can I suggest this informal process?

* If a maintainer approves a PR, and no other maintainers have touched it for at least a week then they can feel free to merge it
* Otherwise all the maintainers who have commented need to agree

This means:
* If only one person has time at the moment, things can still get merged
* If someone doesn't have much time they only have to put a very brief comment ("I have concerns and will come back with them later when I have more time") to stop something they think is not good enough being merged
* If anything does get merged that someone later disagrees with, there's always the fallback of reverting it.

**Comment by jugglerchris** [comment]
I think this can be closed now.
