### ISSUE TITLE
Expose functionality of `lua_dump`

### ISSUE THREAD

**Issue by alvinhochun** [amethyst/rlua#178]
From what I gathered, [`lua_dump`](https://www.lua.org/manual/5.3/manual.html#lua_dump) allows for dumping the compiled bytecode of scripts which in theory can be loaded faster than the script in text form.

**Comment by jugglerchris** [comment]
This has been add as `Function::dump()` as part of #236.  These can be loaded using the (unsafe) `Chunk::into_function_allow_binary()`.  Another option is to use `Lua::unsafe_new_with_flags()` to create the Lua state, which lets you disable the wrappers around the Lua `load` family of functions which normally disable bytecode loading.
