### ISSUE TITLE
How can I use a C/C++ lua library?

### ISSUE THREAD

**Issue by greatzane** [amethyst/rlua#183]
I'm porting my existing C/C++ + lua project to rust + lua using rlua.
I found that the C/C++ lua library can't be used in rlua because the lua_XXX symbols are undefined.
Can I find a way to use these C/C++ lua libraries?

**Comment by crides** [comment]
`rlua` is just a Lua binding, so the Lua library is included. What do you mean by "C/C++ lua library can't be used" then? You shouldn't use the `lua_...` symbols anyway because those are the Lua C API functions. What are you trying to achieve?

**Comment by greatzane** [comment]
Thanks for your reply. I mean third-party C/C++ libraries that provide lua interfaces (e.g. cjson). Is there a way to use these libraries?

**Comment by crides** [comment]
I haven't tried these kind of things out yet, but I'm pretty sure you can. Since you can run any Lua code using `rlua` (because it's just Lua underneath), you should also be able to use other libraries.

**Comment by Erutuon** [comment]
I've had a similar problem when trying to load Lua libraries written in C in scripts loaded by [my program](https://github.com/Erutuon/enwikt-dump-rs/tree/master/process-with-lua) that uses `rlua`. What I came up with, maybe from [this StackOverflow answer](https://stackoverflow.com/a/57595625), was to add a `.cargo/config` file at the top level of my workspace with the following in it:

```toml
[build]
rustflags = ["-C", "link-args=-rdynamic"]
```

**Comment by greatzane** [comment]
> I've had a similar problem when trying to load Lua libraries written in C in scripts loaded by [my program](https://github.com/Erutuon/enwikt-dump-rs/tree/master/process-with-lua) that uses `rlua`. What I came up with, maybe from [this StackOverflow answer](https://stackoverflow.com/a/57595625), was to add a `.cargo/config` file at the top level of my workspace with the following in it:
> 
> ```toml
> [build]
> rustflags = ["-C", "link-args=-rdynamic"]
> ```
> 
> This allowed me to use [`cjson`](https://luarocks.org/modules/openresty/lua-cjson) and [`lua-utf8`](https://github.com/starwing/luautf8) and [`lutf8proc`](https://github.com/Erutuon/lutf8proc) in my scripts; they needed to be able to access the symbols in the Lua C API.

Thanks!!! This help me out!!!
