### ISSUE TITLE
How to use LUA's built in print function

### ISSUE THREAD

**Issue by IGBC** [amethyst/rlua#184]
I have an rlua engine hooked up to a game I am writing, and have scripts running. I naively expected the lua internal print function to output to stdout, but instead nothing happens. 

What do I need to hook up to make the print function work?

**Comment by crides** [comment]
Can you please provide more details of your setup? Do you have any examples that you can show (preferably a small one that reproduces the problem)?

**Comment by rustysec** [comment]
Yes this should work natively, but without some additional details on the setup I'm not sure I can provide much assistance.

**Comment by IGBC** [comment]
I resolved my problem, I made a mistake in my LUA file (I am a little rusty, and lua doesn't spit out "that variable doesn't exist" errors)

thank you for you help as it is the act of building a minimal example that lead me to my bug. 

I will now close this as its not a library error.
