### ISSUE TITLE
Having issues with storing Lua functions as callbacks

### ISSUE THREAD

**Issue by crides** [amethyst/rlua#185]
I'm trying to design a system where the core functionalities are provided through Rust, and Lua is used for scripting. I want to be able to provide hook Lua functions as callbacks to events processed by the Rust side, and I'm having trouble resolving the issues.

I have a core `APIState` struct that is a singleton `UserData` object, and the Lua side would add functions to this `struct`. A simplified version of the architecture looks like this:

```rust
impl<'func> EventHandlers<'func> {
    pub fn add_lua(&mut self, pat: &str, f: LuaFunction<'func>) -> Result<()> {
        self.0.push(EventHandler {
            pat: Regex::new(pat)?,
            func: Either::Right(f),
        });
        Ok(())
    }
    // ...
}

struct APIState<'func>(Arc<Mutex<Storage>>, EventHandlers<'func>);

impl<'func> LuaUserData for APIState<'func> {
    fn add_methods<'lua, M: LuaUserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_method_mut("add_event_handler", |_, state, (pat, func): (String, LuaFunction)| {
            state.1.add_lua(&pat, func);
            Ok(())
        });
        // ...
    }
}
```

And I have this error: 

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'lua` due to conflicting requirements
   --> src/script/mod.rs:208:21
    |
208 |             state.1.add_lua(&pat, func);
    |                     ^^^^^^^
    |
note: first, the lifetime cannot outlive the lifetime `'lua` as defined on the method body at 163:20...
   --> src/script/mod.rs:163:20
    |
163 |     fn add_methods<'lua, M: LuaUserDataMethods<'lua, Self>>(methods: &mut M) {
    |                    ^^^^
note: ...so that the types are compatible
   --> src/script/mod.rs:207:17
    |
207 |         methods.add_method("add_event_handler", |_, state, (pat, func): (String, LuaFunction)| {
    |                 ^^^^^^^^^^
    = note: expected `rlua::value::FromLuaMulti<'lua>`
               found `rlua::value::FromLuaMulti<'_>`
note: but, the lifetime must be valid for the lifetime `'func` as defined on the impl at 162:6...
   --> src/script/mod.rs:162:6
    |
162 | impl<'func> LuaUserData for APIState<'func> {
    |      ^^^^^
note: ...so that the types are compatible
   --> src/script/mod.rs:208:21
    |
208 |             state.1.add_lua(&pat, func);
    |                     ^^^^^^^
    = note: expected `&mut event::EventHandlers<'_>`
               found `&mut event::EventHandlers<'func>`
```

I don't really understand what the core problem is, but I think there's a lifetime conflict between the function's lifetime and the lifetime of the context that handles the methods. Those lifetimes are supposed to be the same, but I guess the context that handles the methods can live for a different amount of time? I can't use `'func` for `'lua`, cuz that would violate the trait. I also can't have lifetime contraints, according to the compiler.

From an architectural standpoint, I could pull some of the feature out from Rust to Lua, so that the event handling part would be in Lua, and there's no data passing needed. But in that case I would lose all the great feature of Rust, and better off writing the whole thing in Lua/Python.

Note: this is not upstream `rlua`. I made one change where I `unsafe impl<'l> Send for LuaFunction<'l> {}` cuz `Lua` is `Send`, and the thing preventing from `Function` to be sent was the raw pointer, which is the same as in `Lua`, so I think it's safe to make `Function` (and other ref values) to be `Send` too?

**Comment by crides** [comment]
I think I know what the problem is. `'lua` is the lifetime of the `LuaContext`, and `'func` is the lifetime of the `LuaFunction` within the `EventHandlers`. The 2 sources have no intersection on declaration, but we humans know in this case they are the same because the only way we can get `LuaFunction`s is from the `LuaContext`. So a bodge would be to `unsafe`ly `transmute` the lifetimes, but I think there should be a safe Rust solution I'm missing.

**Comment by jugglerchris** [comment]
Hi,

Sorry for the long delay before a reply!

I'm afraid you can't have direct references to Lua objects like that - the `LuaFunction<'lua>` is really a proxy pointing to a slot on the Lua stack - after `add_lua()` returns it wouldn't be valid (i.e. the lifetimes are there for a reason!).   This is just how Lua works - the Lua C API doesn't have a function type you can use either; to call a Lua function you have to refer to a stack index.

What you should do instead is store the function in the Lua world, and get them when you need to call them.  Some possibilities:
* Keep a Lua table as a [user value](https://docs.rs/rlua/0.17.0/rlua/struct.AnyUserData.html#method.set_user_value) in your `UserData` object, and store the functions there in your `add_lua` method.
* Keep a Lua table the registry or a global table.

**Comment by crides** [comment]
Thanks for the suggestions! I tried both out, and I have some questions:

1. Setting user values is only availble for `AnyUserData`, but in `add_method_mut` (or `add_method`) only a reference to the actual type is availble. There is `ctx.create_userdata`, but I don't think that's the correct way to do this.
2. Since `named_registry_value` and `registry_value` clones the data, I do need to set the registry values again after I do something with it (like adding a handler to it) right?

**Comment by kyren** [comment]
For functions you can also use Function::bind to bind arguments, and the Lua garbage collector understands those.

**Comment by jugglerchris** [comment]
Hi @crides ,

1. Right, the in `add_method_mut` you're only setting up the type - but at some point you'll create the actual userdata and that's where I'd expect to set the uservalue.
2. `named_registry_value` doesn't necessarily clone the data.  If you've set a registry value to a Lua table, then you can get a reference to that table out:

```rust
let tab: Table<'lua> = ctx.named_registry_value("some_name")?;
```
You can then manipulate `tab` - get/set values etc. and it is altering the same table as is in the registry.

I hope that makes sense (and that I've got it right!).

**Comment by jugglerchris** [comment]
I believe this has been addressed.
