### ISSUE TITLE
Modules and Require

### ISSUE THREAD

**Issue by milse113** [amethyst/rlua#212]
It would be nice if it was possible to use scripts with each-other using the require function, if not the larger Lua ecosystem

**Comment by jugglerchris** [comment]
Hi,
`require` should work - the Lua interpreter itself is unmodified (though `rlua` has wrapped versions of a small number of standard library functions).  Have you tried to use it and had any problems?

**Comment by jugglerchris** [comment]
I'm assuming this has been addressed - please re-open if not!
@atweiden Thanks for the link - that looks nice!
