### ISSUE TITLE
Nice to have: rlua::String could use Eq and Hash

### ISSUE THREAD

**Issue by singalen** [amethyst/rlua#216]
I tried to collect `rlua::String`s into a HashSet (inside a Function) and found that it has neither `Eq` nor `Hash`.
I can convert them to `std::String`s, but I believe it will lead to excess copies.

**Comment by jugglerchris** [comment]
These both look like good ideas to me!  `Eq` can just be derived, and the `Hash` implementation can hash `String::as_bytes()`.
