### ISSUE TITLE
Make create_function/_mut work on reference arguments?

### ISSUE THREAD

**Issue by singalen** [amethyst/rlua#220]
I'm trying to create a function that would mutate its arguments (UserData, if it's important).
Sadly, looks like it's not supported. 
I feel that this should be possible (note `&mut` in front of argument).
```
lua_ctx.create_function_mut(|lua_ctx: Context, (who, to): (&mut EcsProxy, Point)| {
    if let Some(mob) = &mut who.mob {
        mob.plan = Some(MobPlan::WalkTo(to));
    }
    Ok(())
})?;
```

It's not necessary, as all the necessary state is available in globals, but would be nice to have. 

Is there a way at all to obtain a reference to a `UserData` object from a `Context`, or should I use `LightUserData` and store objects outside of context? There should be, because at least methods have access to it.

**Comment by jugglerchris** [comment]
Hi,
I don't think it's possible to get an `&mut` reference like that passed to the function directly because of some awkward lifetimes.
However you can do it slightly indirectly via `AnyUserData`:
```
let f = lua.create_function(|_, (who, to): (AnyUserData, Point)| {
    let mut who = who.borrow_mut::<EcsProxy>()?;
    // use who (which is a `cell::RefMut<EcsProxy>`, and behaves almost exactly like a `&mut`
})?;
```

You can also get a reference directly within the `Lua::context()` callback.  For example, if it's in a global variable:

```
lua.context(|ctx| {
    let my_ecs = globals.get::<_, AnyUserData>("ecs_global")?;
    let my_ecs = my_ecs.borrow::<EcsProxy>()?;
    // my_ecs is a cell::Ref<EcsProxy>
});
```

**Comment by singalen** [comment]
Thank you! I think this is sufficient.
I, OTOH, have found that `add_method_mut` does provide a mut reference to `this` (but I haven't made it to work yet).
Does it mean that there is a way?

**Comment by jugglerchris** [comment]
There's an example of `add_method_mut()` in the tests: https://github.com/amethyst/rlua/blob/master/tests/userdata.rs#L38 in case that helps.
It roughly works by creating a wrapper function which receives the `AnyUserData`, uses `borrow_mut()` and then calls the method you provide.  You could do something similar.
Be aware that if you ever try to get a second mutable reference to the same UserData rlua will panic.

**Comment by singalen** [comment]
I mean, isn’t it a sign that a free-standing functions can also pass their arguments by reference?

**Comment by jugglerchris** [comment]
I don't think it's possible to implement `FromLua for &mut T` to make it work with `create_function` as it is (but happy to be proved wrong!)
As you point out it's possible to handle specific cases (known user data as first parameter for methods), but I'm not sure there's a way to do it generically.
