### ISSUE TITLE
Advice for saving / loading an already-executing lua state.

### ISSUE THREAD

**Issue by RobDavenport** [amethyst/rlua#247]
Trying to do some game state saving/loading for a game with lua functionality, is there any way I can "save" that current lua struct, its context, or a collection of the inner variables? I understand I can grab the `.globals()` which returns a `Table` which is `.clone()` able, but honestly I'm not too familiar with the inner workings of the internal lua state and what this actually means. As I also understand `Context` implements Clone, but when trying to reason about threads and what not I'm running out of ideas.

Unfortunately for my use case, it's not feasible to write a Rust-side type to serialize into, as I have no control over what kinds of variables the script will build. Unless I can serialize to-from something like a `HashMap<Value, Value>` and push that into context while loading.

Any suggestions on how to proceed with this? Ideally if I could just do a big memcpy with the running VM (or something similar) this would provide desire effect. Note that all of the saving/loading will function similarly to rollback where I'd want to go a few 'states' back in time and re-simulate with new input values, whilst saving those corrected states to potentially be rolled back to later.

Updates: Having some luck using _ENV and deep copies, but it seems like the first time I roll back, every subsequent rollback goes back to that original state. Having trouble wrapping my head around how loaded functions interact with _ENV and registry values.

**Comment by jugglerchris** [comment]
Hi,
I'm afraid that cloning anything from the Rust API isn't going to do what you want - most of the Rust types are just handles (and are only valid within the `Context` callback).  `memcpy` isn't going to work (short of `fork()` to a new process) as Lua can do allocations and has a GC.

Full serialisation of state is possible but non trivial (given the complicated graphs of objects, upvalues for functions, etc.).  You could look into things like [Pluto](http://lua-users.org/wiki/PlutoLibrary) (there may be other similar projects).

If you can restrict the saved data supported to a smaller subset of types, that would make it a lot easier.

If you can find some way of solving it on the Lua side, it should be possible to get that working with rlua.

**Comment by jugglerchris** [comment]
> Updates: Having some luck using _ENV and deep copies, but it seems like the first time I roll back, every subsequent rollback goes back to that original state. Having trouble wrapping my head around how loaded functions interact with _ENV and registry values.

If you have a smallish example showing the problem I'm happy to take a look.

**Comment by RobDavenport** [comment]
@jugglerchris thanks for the help! Here's a super slimmed down version of what I'm trying to accomplish. I've also tried to include some comments about what I'm doing in the actual project.

```
use rlua::{Function, Lua, Number, Table};

fn main() {
    let lua = Lua::default();
    let mut current_frame = 0;

    // Initialization code
    let (update_blob, mut update_fn, snapshots) = lua.context(|ctx| {
        // Load the script
        ctx.load(CODE).exec().unwrap();

        // Find the update function and compile it to a blob
        let update_fn: Function = ctx.globals().get("update").unwrap();
        let update_fn_key = ctx.create_registry_value(update_fn.clone()).unwrap();

        // Save it in the registry for later
        let update_blob = update_fn.dump().unwrap();
        let update_blob = ctx.create_registry_value(update_blob).unwrap();

        // Call initialize
        let init: Function = ctx.globals().get("init").unwrap();
        init.call::<_, ()>(()).unwrap(); // Initialize our state with a value of 2

        // Initialize our snapshot buffer with the first entry at 0
        let snapshots = ctx.create_table().unwrap();
        let cloned_state: Table = ctx.load(CLONE_STATE).eval().unwrap();
        snapshots.set(current_frame, cloned_state).unwrap();
        let snapshots = ctx.create_registry_value(snapshots).unwrap();

        // Just for sanity, print our output: 2
        let val: Number = ctx.globals().get("VAL").unwrap();
        println!("VAL: {}", val);

        // Return the stuff for later
        (update_blob, update_fn_key, snapshots)
    });

    // "Running Code" - pt 1 - This will loop the game and update/draw
    // indefinitely until a rollback is necessary. We also save the game state
    // each iteration (in the actual project we use a circular buffer, with
    // length MAX_ROLLBACK_FRAMES + 2 and just modulo into it)
    lua.context(|ctx| {
        // Let's update and save after each iteration
        // I know I don't need to recompile/reload here but I do so in the
        // 2nd part to set the _ENV
        let update_blob: Vec<u8> = ctx.registry_value(&update_blob).unwrap();
        let update_fn = unsafe { ctx.load(&update_blob).into_function_allow_binary().unwrap() };
        let snapshots: Table = ctx.registry_value(&snapshots).unwrap();

        (0..5).for_each(|_| {
            current_frame += 1;
            update_fn.call::<_, ()>(()).unwrap();

            // Generates a new deep copy to save in our snapshot buffer
            let cloned_state: Table = ctx.load(CLONE_STATE).eval().unwrap();
            snapshots.set(current_frame, cloned_state).unwrap();

            // Print our outputs... [4, 8, 16, 32]
            let val: Number = ctx.globals().get("VAL").unwrap();
            println!("VAL: {}", val);
        })
    });

    // "Rolling Back" - Let's roll back to frame index 2, where Val should be 8.
    // Network conditions have triggered a rollback, need to restore to a previous state.
    // We do this by just throwing away our current state and cloning the previous state.
    lua.context(|ctx| {
        // Roll back to this frame
        println!("Rolling back!");
        current_frame = 2;

        // Get our snapshots, specifically the one from index 2
        let snapshots: Table = ctx.registry_value(&snapshots).unwrap();
        let table_to_copy: Table = snapshots.get(current_frame).unwrap();

        // Check our value
        let rolled_back_value: usize = table_to_copy.get("VAL").unwrap();
        println!("Rolled Back Value: {}", rolled_back_value);
        assert_eq!(rolled_back_value, 8);

        // Perform a copy of the table in case we need to roll back again
        // This is annoyingly a function that returns a function, since
        // I can't figure out how to just declare a function to call later
        // without using globals() - which runs the risk of a collision on
        // user scripts
        let new_env = ctx
            .load(DEEP_COPY)
            .call::<(), Function>(())
            .unwrap()
            .call::<Table, Table>(table_to_copy)
            .unwrap();

        // Hook up the update function to use this new _ENV
        let update_fn_blob: Vec<u8> = ctx.registry_value(&update_blob).unwrap();
        let new_update_fn = unsafe {
            ctx.load(&update_fn_blob)
                .set_environment(new_env)
                .unwrap()
                .into_function_allow_binary()
                .unwrap()
        };

        // Remove & Replace the old registries
        let new_update_fn = ctx.create_registry_value(new_update_fn).unwrap();
        let to_replace = std::mem::replace(&mut update_fn, new_update_fn);
        ctx.remove_registry_value(to_replace).unwrap();
    });

    // "Running Code" - pt 2
    // After rolling back, we can proceed as normal, since during the rollback
    //
    lua.context(|ctx| {
        // Let's update and save after each iteration
        let update_fn: Function = ctx.registry_value(&update_fn).unwrap();
        let snapshots: Table = ctx.registry_value(&snapshots).unwrap();

        (0..5).for_each(|_| {
            current_frame += 1;
            update_fn.call::<_, ()>(()).unwrap();

            // Generates a new deep copy to save in our snapshot buffer
            let cloned_state: Table = ctx.load(CLONE_STATE).eval().unwrap();
            snapshots.set(current_frame, cloned_state).unwrap();

            // Print our outputs... [8, 16, 32, 64, 128]
            let val: Number = ctx.globals().get("VAL").unwrap();
            println!("VAL: {}", val);
        })
    });

    // Output should be...
    // VAL: 2
    // VAL: 4
    // VAL: 8
    // VAL: 16
    // VAL: 32
    // VAL: 64
    // Rolling back!
    // Rolled Back Value: 8
    // VAL: 16
    // VAL: 32
    // VAL: 64
    // VAL: 128
    // VAL: 256

    // But actual output is...
    // VAL: 2
    // VAL: 4
    // VAL: 8
    // VAL: 16
    // VAL: 32
    // VAL: 64
    // Rolling back!
    // Rolled Back Value: 8
    // VAL: 64 <--- What is happening here?
    // VAL: 64 <--- Why is update being called but nothing is changing?
    // VAL: 64
    // VAL: 64
    // VAL: 64
}

const CODE: &str = r#"
function init()
    VAL = 2
end

function update()
    VAL = VAL * 2
end
"#;

const CLONE_STATE: &str = r#"
function clone_state(orig, copies)
    copies = copies or {}
    local orig_type = type(orig)
    local copy
    if orig_type == 'table' then
        if copies[orig] then
            copy = copies[orig]
        else
            copy = {}
            copies[orig] = copy
            for orig_key, orig_value in next, orig, nil do
                copy[clone_state(orig_key, copies)] = clone_state(orig_value, copies)
            end
            setmetatable(copy, clone_state(getmetatable(orig), copies))
        end
    else -- number, string, boolean, etc
        copy = orig
    end
    return copy
end
return clone_state(_ENV)"#;

const DEEP_COPY: &str = r#"
function deep_copy(orig, copies)
    copies = copies or {}
    local orig_type = type(orig)
    local copy
    if orig_type == 'table' then
        if copies[orig] then
            copy = copies[orig]
        else
            copy = {}
            copies[orig] = copy
            for orig_key, orig_value in next, orig, nil do
                copy[deep_copy(orig_key, copies)] = deep_copy(orig_value, copies)
            end
            setmetatable(copy, deep_copy(getmetatable(orig), copies))
        end
    else -- number, string, boolean, etc
        copy = orig
    end
    return copy
end
return deep_copy"#;
```

**Comment by jugglerchris** [comment]
Hi,
I've had a chance to look at your code.  After the rollback you've given the update function a new `_ENV`, but you're reading `VAL` from the old environment (i.e. the original globals table).
I made a small hacky change to read `VAL` from the new `_ENV` (https://gist.github.com/jugglerchris/415c1b6e328037b23171ba1a8c1971f4):
```
VAL: 2
VAL: 4
VAL: 8
VAL: 16
VAL: 32
VAL: 64
Rolling back!
Rolled Back Value: 8
VAL: 16
VAL: 32
VAL: 64
VAL: 128
VAL: 256
```
As a side note the Lua C API allows updating the upvalues on an existing function (in this case rebinding `_ENV`) without reloading.  If loading the bytecode is a significant performance issue rlua could at least have an `unsafe` function to set upvalues - I'd have to look into whether it could be done safely (it wouldn't be safe to change upvalues on some functions generated by rlua internally, but for cases like this it seems fine).

**Comment by RobDavenport** [comment]
@jugglerchris thanks for looking into it and the fixed/improved code. I know it was quite a lot of code to look through. Regarding your fix - after going through it a few times I think I understand what the issue was.  So does this mean that my initial code, the "update" function was running correctly on the new `_ENV` with the correct upvalues but my print outs we're simply "targeting" the wrong place? 

I guess what this means is I can run basic initialization using `.globals()`, then keep two registry on hand for state storage and manipulation: one for the "current active state," and another array to represent "possible_rollback_states." Then it just becomes a matter of copying tables in and out of the active state and rollback state array. 

> As a side note the Lua C API allows updating the upvalues on an existing function (in this case rebinding `_ENV`) without reloading. If loading the bytecode is a significant performance issue rlua could at least have an `unsafe` function to set upvalues - I'd have to look into whether it could be done safely (it wouldn't be safe to change upvalues on some functions generated by rlua internally, but for cases like this it seems fine).

Not too sure about this yet. I'll need to try and hook up my above plan to the current project and see if it actually becomes a performance issue or not. I'm still quite new to manipulating the VM state like this so I really am not able to comment. Lua is actually a lot more complex than I thought 😄 . Feel free to close the issue, unless you want to use this as a tracker for the above suggestion.

**Comment by jugglerchris** [comment]
Hi,

Yep, the update was running correctly but you were looking at the last answer from before the rollback.

I think after a while there's a later stage when Lua turns out to be simpler than you previously thought too.  :-)
