### ISSUE TITLE
Capturing stdout

### ISSUE THREAD

**Issue by makspll** [amethyst/rlua#250]
I want to capture and forward the standard output of Lua scripts and forward it to a console internal to the application, does Rlua support this functionality in any way currently ?

**Comment by jugglerchris** [comment]
There's nothing rlua-specific, but at the Lua level you can replace the global `print` function (and if needed `io.write`) to send output elsewhere before running the script.

**Comment by makspll** [comment]
That sounds reasonable, thanks!
