### ISSUE TITLE
custom runtime path

### ISSUE THREAD

**Issue by paulfrische** [amethyst/rlua#282]
Hello there, I think there is no way yet to change the path(s) `require` searches in when requiring other modules. Is the solution to just write your own `require`?

**Comment by jugglerchris** [comment]
The builtin Lua `require` is quite configurable: https://www.lua.org/manual/5.4/manual.html#pdf-require

For example you can adjust [package.path](https://www.lua.org/manual/5.4/manual.html#pdf-package.path) as you like, either from Rust or executing some lua.

**Comment by paulfrische** [comment]
Thank you! Maybe an example in the repo wouldn't hurt, would it?

**Comment by jugglerchris** [comment]
Indeed not - and thanks for your contribution!  (#283 )
