### ISSUE TITLE
Why type_name() is private?

### ISSUE THREAD

**Issue by zrkn** [amethyst/rlua#58]
Hi.

When implementing `ToLua`/`FromLua` for custom types it would've been handy to have access to type name for returning it in `ConversionError`. Maybe make it public? Or add utility method for creating `ConversionError`s with apropriate to/from values?

**Comment by jonas-schievink** [comment]
It shouldn't do any harm to make `type_name` public, but I also envision the sort of helper method you want as part of #60 (should that ever be implemented)

**Comment by jugglerchris** [comment]
`Value::type_name()` is now public.
