### ISSUE TITLE
How to set methods after creating userdata?

### ISSUE THREAD

**Issue by torkleyy** [amethyst/rlua#59]
I have a map of methods that I want to add to my userdata. However, I can't pass anything to `UserData::add_methods`. Is there a way to set methods after I created the user data?

**Comment by torkleyy** [comment]
I've created a workaround for now: https://github.com/rustgd/rlua/commit/b54f9ef12656065803a1860c61b1aa69f4e8e2c9

**Comment by jonas-schievink** [comment]
This could potentially be solved by replacing `UserDataMethods` with a more general `MetaTable` type that provides similar (and more) helpers. Then we could give `AnyUserData` and `Table` a getter for their `MetaTable`.

**Comment by kyren** [comment]
Not saying I'm not willing to do that, but it would require changing userdata metatables to being shared single instances to individual tables per metadata.

I guess one possibility would be to do both, where the default is the shared default metatable and it could be shallow cloned on mutation, but it's a pretty involved change.

Another possibility is simply to override the index metamethod.

**Comment by jugglerchris** [comment]
Closing as this would be a significant design change which I don't think is needed.
