### ISSUE TITLE
Consider hiding `Error` internals

### ISSUE THREAD

**Issue by jonas-schievink** [amethyst/rlua#60]
Currently, adding a variant to `Error` (or changing an existing one) is a breaking change. This happens pretty frequently during development. We could prevent that by making `Error` a struct with a few helper methods to create a specific error, and make the internal enum private so it's not part of the API.

This is probably not that important right now, but when rlua gets closer to a 1.0 release it could allow more freedom in expanding rlua's internals (better error messages, more distinguished error cases without a breaking change). I'm just opening this issue to get a bit of feedback.

**Comment by Timidger** [comment]
If you do this, it would make it harder to remember to `match` on specific error cases, especially when there's a change and e.g an error is made more specific.

Though if you're thinking of changing the error system, might I suggest the new [failure crate](https://github.com/withoutboats/failure)?

**Comment by jonas-schievink** [comment]
> If you do this, it would make it harder to remember to match on specific error cases, especially when there's a change and e.g an error is made more specific.

Do you have an example where this is useful? I've mostly returned elaborate error messages from within callbacks (ie. where the error actually happens), not after catching an error that happened elsewhere.

> Though if you're thinking of changing the error system, might I suggest the new failure crate?

That's probably a good idea, but it does pull in an additional dependency.

**Comment by torkleyy** [comment]
The way I avoid this problem usually is to add another variant, `__NonExhaustive` with `#[doc(hidden)]` and a doc comment saying that you shall never match against it, so you need to have a `_` pattern. This would make adding errors a non-breaking change. Changing an error obviously still is a breaking change.

**Comment by jugglerchris** [comment]
Closing as this is out of date (`Error` has changed to use `failure` and then back again in that time).
