### ISSUE TITLE
copy pasted the example, didn't build

### ISSUE THREAD

**Issue by dataf3l** [amethyst/rlua#91]
error[E0277]: the trait bound `std::string::String: std::convert::From<&std::string::String>` is not satisfied
  --> src/main.rs:25:28
   |
25 |                     editor.add_history_entry(&line);
   |                            ^^^^^^^^^^^^^^^^^ the trait `std::convert::From<&std::string::String>` is not implemented for `std::string::String`
   |
   = help: the following implementations were found:
             <std::string::String as std::convert::From<&'a str>>
             <std::string::String as std::convert::From<std::borrow::Cow<'a, str>>>
             <std::string::String as std::convert::From<std::boxed::Box<str>>>
   = note: required because of the requirements on the impl of `std::convert::Into<std::string::String>` for `&std::string::String`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `rlua`.

To learn more, run the command again with --verbose.

here is my toml file:

[dependencies]
rlua= "*"
rustyline="*"

and the example code (from the repo, unmodified):

//! This example shows a simple read-evaluate-print-loop (REPL).

extern crate rlua;
extern crate rustyline;

use rlua::{Error, Lua, MultiValue};
use rustyline::Editor;

fn main() {
    let lua = Lua::new();
    let mut editor = Editor::<()>::new();

    loop {
        let mut prompt = "> ";
        let mut line = String::new();

        loop {
            match editor.readline(prompt) {
                Ok(input) => line.push_str(&input),
                Err(_) => return,
            }

            match lua.eval::<MultiValue>(&line, None) {
                Ok(values) => {
                    editor.add_history_entry(&line);
                    println!(
                        "{}",
                        values
                            .iter()
                            .map(|value| format!("{:?}", value))
                            .collect::<Vec<_>>()
                            .join("\t")
                    );
                    break;
                }
                Err(Error::SyntaxError {
                    incomplete_input: true,
                    ..
                }) => {
                    // continue reading input and append it to `line`
                    line.push_str("\n"); // separate input lines
                    prompt = ">> ";
                }
                Err(e) => {
                    eprintln!("error: {}", e);
                    break;
                }
            }
        }
    }
}

did I use the wrong version?

**Comment by dataf3l** [comment]
Ok, it looks like removing the & works.
Let's hope removing that & doesn't byte me in the behind in the near future.

Still, I think the example should be updated.

**Comment by dataf3l** [comment]
Can the example clearly indicate the version numbers for the dependencies, so other people aren't bitten by this?
I know just putting a star and expecting it to work was lazy on my side...

**Comment by kyren** [comment]
It’s in cargo.toml, I’m not sure where else it should be indicated.  I probably shouldn’t have left it depending on an old version, but I didn’t even know about rustyline 2.0 until you mentioned this.

Would it be better if the examples were a sub-crate with its own example cargo.toml?

Do people usually do that?

**Comment by dataf3l** [comment]
I think examples should be their own subfolder, and have their own dependencies, no?
That's just my opinion though, others may think differently, and also, I'm new to Rust, I've been cding in rust for only 2 years.

**Comment by kyren** [comment]
This specific issue was fixed, but the general issue that sometimes the example is either out of date with the latest versions of crates, or that versions of `rlua` that are on crates.io are out of date with the examples in github still exists.

One thing I could do is link to the examples from a released tag in the README?

**Comment by Timidger** [comment]
If the example lives in examples/ subdirectory you can specify specific versions which should fix this issue, unless I misunderstand the problem

**Comment by kyren** [comment]
> If the example lives in examples/ subdirectory you can specify specific versions which should fix this issue, unless I misunderstand the problem

you mean by having the examples in a sub-crate, or just in Cargo.toml like I'm doing now?  I might not be familiar with what you're suggesting?

**Comment by Timidger** [comment]
If you have in the TOML that what I was suggesting, ignore me I didn't read the entire issue in detail.

**Comment by jugglerchris** [comment]
Closing as I believe this has been dealt with.
